import { writeFileSync } from 'fs'
import { join } from 'path'
import { clipboard, BrowserWindow } from 'electron'

/**
 * Generate professional meeting minutes in Markdown format.
 */
export function generateMarkdown(minutes: any): string {
  let md = ''

  // Header
  md += `# ${minutes.title}\n\n`
  md += `**Date:** ${formatDate(minutes.date)}`
  if (minutes.duration) {
    md += ` | **Duration:** ${formatDuration(minutes.duration)}`
  }
  md += '\n'
  if (minutes.location) {
    md += `**Location:** ${minutes.location}`
  }
  if (minutes.chairperson) {
    md += ` | **Chairperson:** ${minutes.chairperson}`
  }
  md += '\n\n'

  // Attendees
  if (minutes.attendees?.length > 0) {
    md += `## Attendees\n`
    md += minutes.attendees.map((a: string) => `- ${a}`).join('\n')
    md += '\n'
    if (minutes.absentees?.length > 0) {
      md += `\n**Apologies:** ${minutes.absentees.join(', ')}\n`
    }
    md += '\n'
  }

  // Agenda
  if (minutes.agenda?.length > 0) {
    md += `## Agenda\n`
    md += minutes.agenda.map((a: string, i: number) => `${i + 1}. ${a}`).join('\n')
    md += '\n\n'
  }

  // Executive Summary
  if (minutes.overview) {
    md += `## Executive Summary\n`
    md += `${minutes.overview}\n\n`
  }

  // Discussion Items
  if (minutes.discussions?.length > 0) {
    md += `## Discussion\n\n`
    minutes.discussions.forEach((d: any, i: number) => {
      md += `### ${i + 1}. ${d.topic}\n`
      md += `${d.discussion}\n`
      if (d.outcome) {
        md += `\n**Outcome:** ${d.outcome}\n`
      }
      md += '\n'
    })
  }

  // Action Items
  if (minutes.actionItems?.length > 0) {
    md += `## Action Items\n\n`
    md += `| # | Action | Owner | Deadline | Status |\n`
    md += `|---|--------|-------|----------|--------|\n`
    minutes.actionItems.forEach((a: any, i: number) => {
      md += `| ${i + 1} | ${a.action} | ${a.owner || 'TBD'} | ${a.deadline || 'TBD'} | ${a.status === 'completed' ? 'Completed' : 'Pending'} |\n`
    })
    md += '\n'
  }

  // Decisions
  if (minutes.decisions?.length > 0) {
    md += `## Decisions Made\n`
    md += minutes.decisions.map((d: string) => `- [x] ${d}`).join('\n')
    md += '\n\n'
  }

  // Closing
  if (minutes.nextMeetingDate || minutes.adjournmentTime) {
    md += `## Closing\n`
    if (minutes.adjournmentTime) {
      md += `**Meeting adjourned at:** ${minutes.adjournmentTime}\n`
    }
    if (minutes.nextMeetingDate) {
      md += `**Next meeting:** ${minutes.nextMeetingDate}\n`
    }
    md += '\n'
  }

  // Full Transcript
  if (minutes.transcript?.length > 0) {
    md += `## Full Transcript\n\n`
    minutes.transcript.forEach((seg: any) => {
      const time = formatTimestamp(seg.start)
      md += `**[${time}]** ${seg.text}\n\n`
    })
  }

  // Footer
  md += `---\n`
  md += `*Minutes generated by DiScreenRecorder on ${formatDate(minutes.generatedAt)}*\n`

  return md
}

/**
 * Export minutes as Markdown file.
 */
export function exportMarkdown(minutes: any, meetingDir: string): string {
  const md = generateMarkdown(minutes)
  const filePath = join(meetingDir, 'minutes.md')
  writeFileSync(filePath, md, 'utf-8')
  return filePath
}

/**
 * Copy minutes to clipboard as Markdown.
 */
export function exportClipboard(minutes: any): string {
  const md = generateMarkdown(minutes)
  clipboard.writeText(md)
  return md
}

/**
 * Export minutes as PDF using Electron's printToPDF.
 */
export async function exportPDF(minutes: any, meetingDir: string): Promise<string> {
  const md = generateMarkdown(minutes)
  const html = markdownToStyledHtml(md, minutes.title)

  const win = new BrowserWindow({
    show: false,
    width: 800,
    height: 1100,
    webPreferences: { offscreen: true }
  })

  try {
    await win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`)

    // Wait a moment for rendering
    await new Promise(resolve => setTimeout(resolve, 500))

    const pdfBuffer = await win.webContents.printToPDF({
      printBackground: true,
      pageSize: 'A4',
      margins: { top: 0.75, bottom: 0.75, left: 0.75, right: 0.75 }
    })

    const pdfPath = join(meetingDir, 'minutes.pdf')
    writeFileSync(pdfPath, pdfBuffer)
    return pdfPath
  } finally {
    win.close()
  }
}

/**
 * Convert markdown-like content to styled HTML for PDF generation.
 */
function markdownToStyledHtml(md: string, title: string): string {
  // Simple markdown to HTML conversion
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Checkbox list items
    .replace(/^- \[x\] (.+)$/gm, '<li class="check">$1</li>')
    // Unordered list items
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Ordered list items
    .replace(/^\d+\. (.+)$/gm, '<li class="ordered">$1</li>')
    // Table rows
    .replace(/^\|(.+)\|$/gm, (match) => {
      if (match.includes('---|')) return '' // Skip separator rows
      const cells = match.split('|').filter(c => c.trim())
      const tag = match.includes('---') ? 'th' : 'td'
      return `<tr>${cells.map(c => `<${tag}>${c.trim()}</${tag}>`).join('')}</tr>`
    })
    // Horizontal rule
    .replace(/^---$/gm, '<hr>')
    // Paragraphs (double newline)
    .replace(/\n\n/g, '</p><p>')

  // Wrap consecutive list items
  html = html.replace(/(<li[^>]*>.*?<\/li>\n?)+/g, '<ul>$&</ul>')

  // Wrap table rows
  html = html.replace(/(<tr>.*?<\/tr>\s*)+/g, '<table>$&</table>')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #333;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    h1 {
      font-size: 20pt;
      color: #1a1a2e;
      text-align: center;
      margin-bottom: 8px;
      border-bottom: 2px solid #1a1a2e;
      padding-bottom: 12px;
    }
    h2 {
      font-size: 13pt;
      color: #1a1a2e;
      margin-top: 24px;
      margin-bottom: 8px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 4px;
    }
    h3 {
      font-size: 11pt;
      color: #333;
      margin-top: 16px;
      margin-bottom: 4px;
    }
    p { margin-bottom: 8px; }
    ul { list-style: none; margin-bottom: 12px; }
    li { padding: 2px 0; padding-left: 16px; position: relative; }
    li::before { content: "\\2022"; position: absolute; left: 0; color: #666; }
    li.check::before { content: "\\2713"; color: #2e7d32; font-weight: bold; }
    li.ordered { list-style-type: decimal; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 12px 0;
      font-size: 10pt;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 6px 10px;
      text-align: left;
    }
    th {
      background: #f5f5f5;
      font-weight: 600;
    }
    tr:nth-child(even) { background: #fafafa; }
    hr { border: none; border-top: 1px solid #ddd; margin: 24px 0; }
    strong { font-weight: 600; }
    em { font-style: italic; color: #666; font-size: 9pt; }
  </style>
</head>
<body>
  <p>${html}</p>
</body>
</html>`
}

// ── Utilities ──

function formatDate(isoString: string): string {
  if (!isoString) return ''
  try {
    return new Date(isoString).toLocaleDateString('en-ZA', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return isoString
  }
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}m ${s}s`
}

function formatTimestamp(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`
}
